server {
    listen 80;
    server_name test.2run2run.click;

    root /var/www/payment-system-frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /css/ {
        try_files $uri =404;
    }

    location /js/ {
        try_files $uri =404;
    }

    location /pages/ {
        try_files $uri =404;
    }

    location = /favicon.ico {
        try_files $uri =404;
        access_log off;
        log_not_found off;
    }

    location = /favicon.svg {
        try_files $uri =404;
        access_log off;
        log_not_found off;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /actuator/health {
        proxy_pass http://127.0.0.1:8080;
    }
}
